- scripts/Neurolearn.ipynb
It looks like `coll_dat` is not being used anywhere in this notebook.
> Removed unused variable

- .travis.yml
- nltools/tests/test_analysis.py
This PR adds a sanity test for `analysis.Predict` and a Travis CI config file. Travis is configured to set up Miniconda with all required dependencies and run pytest.
> Tests and Travis CI config

- nltools/tests/conftest.py
- nltools/tests/test_analysis.py
* Added a [fixture](https://pytest.org/latest/fixture.html) to inject a simulator in each test (except the simulator's own test which will go to a separate module.)
* Removed an unused variable and ran the code through auto-pep8.
> Use a pytest fixture to inject a simulator object 

- nltools/data.py
- nltools/tests/test_data.py
added new threshold and region extraction methods to Brain_Data()
> New region methods

- examples/01_DataOperations/plot_mask.py
- nltools/mask.py
- nltools/tests/test_data.py
Updated create_sphere to accurately find spheres on the mask coordinates. 
Updated example plot_mask.py to reflect change.
> Sphere bug

- nltools/data.py
fixed bug with apply mask.  was only returning single image after applied mask.
> fixed bug with apply_mask

- nltools/analysis.py
forced_choice_idx is added to prevent misuse of forced_choice function in the future.
> adding a forced_choice_idx in Roc.calculate

- nltools/__init__.py
- nltools/analysis.py
- nltools/cross_validation.py
- nltools/data.py
- nltools/datasets.py
- nltools/file_reader.py
- nltools/mask.py
- nltools/stats.py
- nltools/tests/test_data.py
- nltools/utils.py
This pull request fixes #118 and substantially updates formatting to be in better compliance with pep8
> Clean formatting and fix upload bug

- nltools/data.py
- nltools/plotting.py
Added silhouette plot function to plotting.py and as Adjacency method in data.py.
> Added silhouette plot function

- nltools/data.py
Fixed bug in predict cross-validation.  added a ravel for different matrix size.  This bug probably has something to do with an update in a dependency package.
> fixed bug with cross-validation in predict

- nltools/data.py
- nltools/tests/test_data.py
Fixes issue with slicing with Brain_Data noted in issue #165
> updated Brain_Data slicing

- MANIFEST.in
- nltools/data/brain_data.py
- nltools/tests/test_data.py
- nltools/utils.py
- nltools/version.py
- setup.py
adds decomposition to brain_data mentioned in issue #178.  It's like predict for PCA, ICA, etc.
> Add decompose method to brain_data

- examples/02_Analysis/plot_decomposition.py
- nltools/data/brain_data.py
- nltools/tests/test_data.py
as noted in #184.  This allows user to specify decomposition over voxels or images.
> added axis flag to decompose

- nltools/data/brain_data.py
- nltools/tests/test_data.py
> added cosine similarity to Brain_Data.similarity

- nltools/data/adjacency.py
Now supports plotting onto specified axis (ax = ... flag)
Added figsize flag
Reduced dot size to 1
> Updated plot_mds

- nltools/stats.py
- nltools/tests/test_stats.py
deleted line 599 in stats.py which got rid of the grouping column even if it was passed. 
modified return so it would properly return grouping if it was passed. 
wrote tests.
> fixed transform pairwise and added tests

- nltools/stats.py
Refactored trim and winsorize functions. #158
> refactored trim and winsorize to single subfunction

- .travis.yml
- nltools/stats.py
- nltools/tests/test_stats.py
- requirements.txt
changed permutation testing default to two tailed 
added tests.
> Fix perm tail

- examples/plot_adjacency.py
- nltools/data/adjacency.py
- nltools/data/brain_data.py
- nltools/stats.py
- nltools/tests/test_data.py
- nltools/utils.py
Adds conversion from distance to similarity.  Adds faster ttest method. Adds cluster methods. Fixes issues #234, #233
> Updates to Adjacency Class

- nltools/stats.py
cleaned up unused default. 
updated documentation.
> small cleanup on matrix_permutation function

- nltools/data/brain_data.py
- nltools/tests/test_brain_data.py
can perform contrasts by multipling Brain_Data by contrast vector. Fixes issue #279 .
> added vector multiplication to Brain_Data

- nltools/data/brain_data.py
for X and Y indices and columns.
> Quick fix to hdf5 loading so that bytes are converted to string 

- nltools/datasets.py
> fixed bug in fetch_localizer

- .readthedocs.yml
- nltools/data/brain_data.py
swapped corrcoef with pearsonr due to rtd build issues.
> Balanced acc

- nltools/data/adjacency.py
- nltools/data/brain_data.py
- nltools/plotting.py
- nltools/tests/test_adjacency.py
- nltools/tests/test_brain_data.py
added dunder divide methods to brain_data and adjacency classes.  Fixes issue #333
> Add divide

- nltools/data/adjacency.py
- nltools/data/brain_data.py
- nltools/data/design_matrix.py
- nltools/external/srm.py
- nltools/stats.py
- nltools/tests/test_adjacency.py
- nltools/tests/test_brain_data.py
- nltools/tests/test_stats.py
- requirements.txt
- updated SRM code from brainiak
- made substantial changes to how Brain_Data alignment data are stored.
- updated how Brain_Data.align() method works.
- minor code refactoring.
- Added temporary fix to weird plotting issues with newer version of matplotlib. issue #351
ToDo:
- Finish updating tests.
- decide whether to include FastSRM, it's a little more work than I thought it was going to be.
- Fix minor Smoothing Bug.
> Updated Hyperalignment
